name: pixelpop
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  font_awesome_flutter: ^8.10.1  
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

 
  uses-material-design: true


  assets:
    - assets/images/
    - assets/desktop/
    - assets/tablet/
    - assets/mobile/
    - assets/logos/

  